#                       Assignment 9

## Develop an AI Model to Analyze Social Media Sentiment Trends for Financial Markets

### Name: Sanskruti Rane  
### Roll No: 140  
### Class: TY AIDS  
### Division: A

In [1]:
pip install pandas numpy scikit-learn nltk matplotlib seaborn

Requirement already satisfied: pandas in ./anaconda3/lib/python3.9/site-packages (2.1.4)
Requirement already satisfied: numpy in ./anaconda3/lib/python3.9/site-packages (1.26.4)
Requirement already satisfied: scikit-learn in ./anaconda3/lib/python3.9/site-packages (1.3.2)
Requirement already satisfied: nltk in ./anaconda3/lib/python3.9/site-packages (3.8.1)
Requirement already satisfied: matplotlib in ./anaconda3/lib/python3.9/site-packages (3.9.4)
Requirement already satisfied: seaborn in ./anaconda3/lib/python3.9/site-packages (0.12.2)
Requirement already satisfied: python-dateutil>=2.8.2 in ./anaconda3/lib/python3.9/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in ./anaconda3/lib/python3.9/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in ./anaconda3/lib/python3.9/site-packages (from pandas) (2023.3)
Requirement already satisfied: scipy>=1.5.0 in ./anaconda3/lib/python3.9/site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.1.1 in ./anaconda3/lib/python3.9/site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./anaconda3/lib/python3.9/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: click in ./anaconda3/lib/python3.9/site-packages (from nltk) (8.1.7)
Requirement already satisfied: regex>=2021.8.3 in ./anaconda3/lib/python3.9/site-packages (from nltk) (2023.10.3)
Requirement already satisfied: tqdm in ./anaconda3/lib/python3.9/site-packages (from nltk) (4.65.0)
Requirement already satisfied: contourpy>=1.0.1 in ./anaconda3/lib/python3.9/site-packages (from matplotlib) (1.3.0)
Requirement already satisfied: cycler>=0.10 in ./anaconda3/lib/python3.9/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in ./anaconda3/lib/python3.9/site-packages (from matplotlib) (4.25.0)
Requirement already satisfied: kiwisolver>=1.3.1 in ./anaconda3/lib/python3.9/site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: packaging>=20.0 in ./anaconda3/lib/python3.9/site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in ./anaconda3/lib/python3.9/site-packages (from matplotlib) (10.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in ./anaconda3/lib/python3.9/site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: importlib-resources>=3.2.0 in ./anaconda3/lib/python3.9/site-packages (from matplotlib) (6.1.1)
Requirement already satisfied: zipp>=3.1.0 in ./anaconda3/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib) (3.17.0)
Requirement already satisfied: six>=1.5 in ./anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [7]:
import pandas as pd

df = pd.read_csv("twitter_sentiment.csv")

print(df.head())

   4  3  Mon May 11 03:17:40 UTC 2009  kindle2        tpryan  \
0  4  4  Mon May 11 03:18:03 UTC 2009  kindle2        vcu451
1  4  5  Mon May 11 03:18:54 UTC 2009  kindle2        chadfu
2  4  6  Mon May 11 03:19:04 UTC 2009  kindle2         SIX15
3  4  7  Mon May 11 03:21:41 UTC 2009  kindle2      yamarama
4  4  8  Mon May 11 03:22:00 UTC 2009  kindle2  GeorgeVHulme

  @stellargirl I loooooooovvvvvveee my Kindle2. Not that the DX is cool, but the 2 is fantastic in its own right.
0  Reading my kindle2...  Love it... Lee childs i...
1  Ok, first assesment of the #kindle2 ...it fuck...
2  @kenburbary You'll love your Kindle2. I've had...
3  @mikefish  Fair enough. But i have the Kindle2...
4  @richardebaker no. it is too big. I'm quite ha...

In [11]:
df = pd.read_csv("twitter_sentiment.csv", encoding='latin-1', header=None)

df.columns = ["sentiment","id","date","query","user","tweet"]

df.head()

,sentiment,id,date,query,user,tweet
0,4,3,Mon May 11 03:17:40 UTC 2009,kindle2,tpryan,@stellargirl I loooooooovvvvvveee my Kindle2. ...
1,4,4,Mon May 11 03:18:03 UTC 2009,kindle2,vcu451,Reading my kindle2... Love it... Lee childs i...
2,4,5,Mon May 11 03:18:54 UTC 2009,kindle2,chadfu,"Ok, first assesment of the #kindle2 ...it fuck..."
3,4,6,Mon May 11 03:19:04 UTC 2009,kindle2,SIX15,@kenburbary You'll love your Kindle2. I've had...
4,4,7,Mon May 11 03:21:41 UTC 2009,kindle2,yamarama,@mikefish Fair enough. But i have the Kindle2...

In [13]:
df['sentiment'].value_counts()

sentiment
4    198
0    178
2    140
Name: count, dtype: int64

In [19]:
print(df.columns)

Index(['sentiment', 'id', 'date', 'query', 'user', 'tweet'], dtype='object')

In [21]:
import re

def clean_text(text):
    
    text = str(text)
    
    text = re.sub(r"http\S+","",text)
    
    text = re.sub("@[A-Za-z0-9_]+","",text)
    
    text = re.sub("[^a-zA-Z]"," ",text)
    
    text = text.lower()
    
    return text

df['clean_tweet'] = df['tweet'].apply(clean_text)

In [23]:
df.head()

,sentiment,id,date,query,user,tweet,clean_tweet
0,4,3,Mon May 11 03:17:40 UTC 2009,kindle2,tpryan,@stellargirl I loooooooovvvvvveee my Kindle2. ...,i loooooooovvvvvveee my kindle not that the...
1,4,4,Mon May 11 03:18:03 UTC 2009,kindle2,vcu451,Reading my kindle2... Love it... Lee childs i...,reading my kindle love it lee childs i...
2,4,5,Mon May 11 03:18:54 UTC 2009,kindle2,chadfu,"Ok, first assesment of the #kindle2 ...it fuck...",ok first assesment of the kindle it fuck...
3,4,6,Mon May 11 03:19:04 UTC 2009,kindle2,SIX15,@kenburbary You'll love your Kindle2. I've had...,you ll love your kindle i ve had mine for a...
4,4,7,Mon May 11 03:21:41 UTC 2009,kindle2,yamarama,@mikefish Fair enough. But i have the Kindle2...,fair enough but i have the kindle and i th...

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000)

X = tfidf.fit_transform(df['clean_tweet'])

y = df['sentiment']

In [27]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [29]:
model = LogisticRegression()

model.fit(X_train, y_train)

LogisticRegression()

In [31]:
y_pred = model.predict(X_test)

In [33]:
print("Accuracy:", accuracy_score(y_test,y_pred))

print(classification_report(y_test,y_pred))

Accuracy: 0.6923076923076923
              precision    recall  f1-score   support

           0       0.66      0.70      0.68        27
           2       0.76      0.43      0.55        30
           4       0.69      0.85      0.76        47

    accuracy                           0.69       104
   macro avg       0.70      0.66      0.66       104
weighted avg       0.70      0.69      0.68       104

In [35]:
tweet = ["Reliance stock is performing very well today"]

tweet_clean = [clean_text(t) for t in tweet]

tweet_vec = tfidf.transform(tweet_clean)

prediction = model.predict(tweet_vec)

print("Sentiment:", prediction)

Sentiment: [0]